version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
    - SPRING_DATASOURCE_USERNAME=stat
    - SPRING_DATASOURCE_PASSWORD=1234




  stats-db:
    image: postgres:15-alpine
    container_name: stats-db
    ports:
      - "6789:5432"

    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=1234

  ewm-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
      - stats-server
      - ewm-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
    - SPRING_DATASOURCE_USERNAME=stat
    - SPRING_DATASOURCE_PASSWORD=1234

  ewm-db:
    image: postgres:15-alpine
    container_name: ewm-db
    ports:
      - "6790:5432"
    environment:
      - POSTGRES_DB=mainDb
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=1234





